I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 964, in script
    show azazel bad neutral transparent
Exception: Image 'azazel bad neutral' does not accept attributes 'transparent'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 964, in script
    show azazel bad neutral transparent
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'azazel bad neutral' does not accept attributes 'transparent'.

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.3.22090809
Azazel 1.0
Thu Nov  3 22:42:14 2022
