I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 289, in script
    $ gainGood()
  File "game/script.rpy", line 289, in <module>
    $ gainGood()
  File "game/script.rpy", line 74, in gainGood
    moralityScore += 1
UnboundLocalError: local variable 'moralityScore' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 289, in script
    $ gainGood()
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Downloads\Software\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 289, in <module>
    $ gainGood()
  File "game/script.rpy", line 74, in gainGood
    moralityScore += 1
UnboundLocalError: local variable 'moralityScore' referenced before assignment

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.3.22090809
Azazel 1.0
Tue Nov  1 07:29:45 2022
